version: '3.7'
networks:
    enena_network:
        name: enena_network
        driver: bridge

services:
    nginx:
        image: nginx
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        volumes:
            - wordpress:/var/www/html
        networks:
            - enena_network
        ports:
            - 443:443
        depends_on:
            - wordpress
    wordpress:
        image: wordpress
        build:
            context: ./requirements/wordpress/
            dockerfile: Dockerfile
        container_name: wordpress
        restart: always
        volumes:
            - wordpress:/var/www/html
        networks:
            - enena_network
        depends_on: 
            - mysql
        expose:
            - "9000"
        env_file: .env
    mysql:
        image: mariadb
        build:
            context: ./requirements/mariadb/
            dockerfile: Dockerfile
        container_name: mariadb
        restart: always
        volumes:
            - mariadb:/var/lib/mysql
        networks:
                - enena_network
        expose:
            - "3306"
        env_file: .env


volumes:
    wordpress:
        driver: local
        name: wordpress
        driver_opts:
            type: none
            o: bind
            device: /home/enena/data/wp
    mariadb:
        driver: local
        name: mariadb
        driver_opts:
            type: none
            o: bind
            device: /home/enena/data/db
