version: '3.7'
networks:
    enena_network:
        name: enena_network
        driver: bridge

services:
    mysql:
        image: mariadb
        volumes:
            - mariadb:/var/lib/mysql
        env_file: .env
        build: ./requirements/mariadb/
        restart: always
        networks:
            - enena_network
        container_name: mariadb
        expose: 
            - "3306"
    wordpress:
        image: wordpress
        volumes:
            - wordpress:/var/www/html
        env_file: .env
        depends_on: 
            - mysql
        build: ./requirements/wordpress/
        restart: always
        networks: 
            - enena_network
        container_name: wordpress
        expose: 
            - "9000"
    nginx:
        build: 
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        volumes:
            - wordpress:/var/www/html
        ports: 
            - 443:443
        depends_on: 
            - wordpress
        networks: 
            - enena_network
        container_name: nginx
        restart: always

volumes:
    wordpress:
        driver: local
        name: wordpress
        driver_opts: 
            type: none
            o: bind
            device: /home/enena/data/wp
    mariadb:
        driver: local
        name: mariadb
        driver_opts: 
            type: none
            o: bind
            device: /home/enena/data/db
